### ISSUE TITLE
`dapple run` sometimes writes in the wrong environment in the dappfile

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#141]
@ryepdx:
https://github.com/nexusdev/dapple/blob/master/lib/workspace.js#L262 is probably the reason
why resolving the envName here? isn't it passed as parameter?

**Comment by ryepdx** [comment]
Yeah, it's passed as a parameter. But there's no guarantee that the passed-in parameter isn't just raw user input. The solution here might be to just throw an exception if the user tries to specify an invalid environment name. It really shouldn't be as forgiving as it currently is.

**Comment by ryepdx** [comment]
Yeah, it's passed as a parameter. But I figured there's no guarantee that the specified environment name has been fully resolved. Would probably be best to make sure we're checking the environment name every time one is specified. Given the number of options shared between commands, it might be a good idea to factor out some of the CLI option-processing code currently duplicated in a few places in `cmd/main.js` into a common option-processing class.

**Comment by nmushegian** [comment]
closable?

**Comment by mhhf** [comment]
closable!
