### ISSUE TITLE
update ethersim

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#142]
Our (ethersim fork) gas calculation is wrong. Gas calculation for a transaction and basefee for different operations have changed in homestead: https://github.com/ethereumjs/common/blob/master/params.json
we calculate less gas than needed which leads to a crash if using homestead parameter on chains.

**Comment by mhhf** [comment]
This is sort of important Homestead will get released in ~2 Weeks
https://blog.ethereum.org/2016/02/29/homestead-release/

**Comment by mhhf** [comment]
@ryepdx if you can give me a quick overview on what you had to change in ethersim in order to make it work I can try to refactor https://github.com/ethereumjs/testrpc into it

**Comment by ryepdx** [comment]
There were a lot of things I had to change, to be honest. Most of the changes you'd have to make to get testrpc working in dapple will probably be related to overriding hardcoded values and outputs, assuming testrpc is less broken than ethersim was.

**Comment by ryepdx** [comment]
Tried switching ti TestRPC and very nearly made it, but there was a race condition I couldn't suss out. Ended up going back to EtherSim and updating it.
