### ISSUE TITLE
Proposal: natspec debugger

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#143]
Low priority for now, but maybe useful Idea to consider later.
For debugging purposes I find it handy to log function execution of a contract. This could be achieved by automatically adding logging for function, gas execution or other log statements by a preprocessor to the contract source. The preprocessor could depend on the environments (internal/ debug flags) or log-level option during deploy. Also formatted log statements could be generated based on the natspec:

```
contract A is Debug {
...
/// @notice foo bar `b*0.25` bazz
/// @dev yay omg yay `a` -> `b` much wow `c`!
function omfg (address a, uint b) returns (bool c) {
...
```

will get transformed in:

```
contract A is Debug {
...
/// @notice foo bar `b*0.25` bazz
/// @dev The author `a` just donated `b/1000` eth: much wow (`c`)!
function omfg (address a, uint b) returns (bool c) {
...
logDev('omfg', a, b, c )
return c;
}
...
```

which produces the output:
`The author 0x5e8c828a48ad0db2054aa6fab15e901c192e93b3 just donated 54.343 eth: much wow (false)`

**Comment by nmushegian** [comment]
This could be done using just the constants preprocessor and some compilation tricks, at the cost of 1 bit of storage (not even set - just unusable):

```
DebugGeneric {
    bool __debug;
    DebugGeneric( bool enable ) {
         __debug = enable;
    }
    function logDev(...) internal {
        if (__debug) {
             ...
        }
}
Debug is DebugGeneric( ENABLE_DEBUG )
```

So the only part that actually gets compiled into the contract if ENABLE_DEBUG is false is that one bit of `__debug`'s storage slot is unusable.

**Comment by ryepdx** [comment]
I think I like @mhhf's suggestion, as it reduces the number of places the information about the logging output gets stored. I'd maybe even either pare it down further to have an implicit event logging statement right before the return, or replace the regular event call with another specially formatted comment. Like:

```
/// @dev The author `a` just donated `b/1000` eth: much wow (`c`)!
function omfg (address a, uint b) returns (bool c) {
...
    /// @logdev
...
}
```

**Comment by nmushegian** [comment]
I think this is done?
