### ISSUE TITLE
Node < 5.* compatibility

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#148]
Since some use cases wont be able to do with node 5.*+ it is maybe good to introduce an intermediate step, which compiles and bundles our ES2015 code. This could make dapple compatible with node 0.10.* .

I stumbled here upon this:
https://github.com/meteor/meteor/issues/6353

Since node 4.*+ support for meteor is not over the corner I'd need to engineer a workaround here. This could be done locally, or global with an intermediate ES2015 -> ES5 step. 

Do you think node 0.10.* support is desirable?

**Comment by ryepdx** [comment]
Does [this](http://info.meteor.com/blog/es2015-get-started) work for you?

Not sure how desirable Node 0.10.* support is at the moment. Would have to dig in and figure out what packages we'd have to downgrade and what we'd end up losing.

**Comment by mhhf** [comment]
ES2015 syntax work in code parsed by meteor, but not included via npm. Its not on scope during this month but necessary for CI like test validation by dapphub.

**Comment by mhhf** [comment]
meteor supports ES2015 syntax now. Shouldn't focus on being backwards compatible with old node now
