### ISSUE TITLE
Avoid deploying Debug contracts

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#155]
In order to prevent people from accidentally deploying code inheriting from the Debug contract,`dapple run` should at minimum check the interfaces of each contract explicitly deployed (ideally each contract implicitly deployed as well, though that might be too difficult at this time) and refuse to proceed if it appears the contract inherits from Debug.

Consider allowing deployment and downgrading the failure to a warning if the `--force` flag is set.

**Comment by nmushegian** [comment]
I'd go as far as suggesting that deployable contracts should be explicitly tagged as `is Deployable`. A majority of contracts so far have been created by other contracts.

**Comment by mhhf** [comment]
what about managing deployable contracts in the dappfile under `contracts`?

**Comment by nmushegian** [comment]
Even better.

**Comment by ryepdx** [comment]
The problem I'm trying to address here is preventing people from adding `is Debug` to a contract in order to log during `dapple test` and then forgetting to take it off before executing `dapple run`. Forcing the user to explicitly define which contracts may be deployed doesn't solve that problem. And to be honest, don't deploy scripts already enforce that kind of explicitness anyway?

**Comment by mhhf** [comment]
sry, I've mistaken some things. We should absolutely check the interface before deploying.
Maybe we can replace the `is Debug` flag with a preprocessor which adds it on internal chains when debug expressions are found: https://github.com/nexusdev/dapple/issues/143
e.g. 
`//@log(uint x)`

**Comment by mhhf** [comment]
Deprecated for v0.8
