### ISSUE TITLE
`dapple version` feature request

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#170]
Would be useful (for debugging and package tracking purposes) to have a `version` command line argument that shows the dapple version number and exits.

```
$ truffle version
Truffle v0.3.1
```

```
$ embark version
1.0.2
```

Workaround (when installed via `npm`):
```
$ npm list -g dapple
/Users/mids/.node/lib
└── dapple@0.3.0
```

**Comment by mhhf** [comment]
Thanks for the Report! This fixes it: https://github.com/nexusdev/dapple/pull/171
