### ISSUE TITLE
deprecated addresses / constants

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#177]
I should be able to mark object names or addresses in the dappfile so that dapple will stop me from linking against them

**Comment by nmushegian** [comment]
My workaround for now is simply deleting objects from the dappfile

**Comment by ryepdx** [comment]
How is deprecating preferable to deleting in this context?

**Comment by nmushegian** [comment]
I suppose I'm stuck in the mindset of the dappfile objects actually being like a transaction receipt log, which is not accurate at all anymore. Closing this, but want to revisit the idea of having a historical overview that doesn't require investigating git history and chain state
