### ISSUE TITLE
get rid name for dapple[<name>] in js_module.js

### ISSUE THREAD

**Issue by wighawag** [nexusdev/dapple#181]
First of all thanks for your work, dapple is cool.

One theing that annoy me is that I'd like to use js_module.js on its own (without browserify or other commonjs loader)

Currently it require me to know the name to get it vai dapple[<name>]

Could we get rid of that name as it does not serve much purpose.
else could we use a constant like "default" 

See:
https://github.com/nexusdev/dapple/blob/56a3f22b3a450674155e41558363af7743d70116/lib/pipelines.js#L28

**Comment by ryepdx** [comment]
So, the reasoning behind that is to allow people to use multiple packages at once, even if they just load the module files directly into their browsers via a script tag. Could definitely add an override option, though!

**Comment by dbrock** [comment]
Is the name overrideable or is it always taken from `process.cwd`? The latter would be bad and even the former is bordering on bad I would say. Doesn't seem entirely kosher to depend on the directory name like that.

**Comment by ryepdx** [comment]
Yup, that's a bad way to do that. Will be switching to using the package name and adding a `--global` CLI option to let users pass in an alternate global variable name.

**Comment by ryepdx** [comment]
@wighawag, does a `--global <variable name>` flag address your issue? Basically lets you replace the `dapple[<name>]` variable with a variable name of your choosing.

**Comment by wighawag** [comment]
Yes that would do it. Thanks!

**Comment by nmushegian** [comment]
https://github.com/nexusdev/dapple/pull/194
