### ISSUE TITLE
tar balls for package content

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#187]

**Comment by ryepdx** [comment]
If you haven't begun work on this issue yet, can you expand on it a bit?

**Comment by mhhf** [comment]
This is a leftover from the hackaton where we found the ipfs sync process slow due to the amount of files. We thought about bundling all files before including them on ipfs.
But this also could cause storing same files in multiple tar balls. So from my perspective this could safely be closed if @dbrock has nothing to add here.

**Comment by ryepdx** [comment]
Closing this now, then.
