### ISSUE TITLE
js_module.js compatibility with meteor

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#195]
The  dapple generated `js_module.js` is hard to use with Meteor…
Due to strict mode I can't seem to define my own `dapple` globally to bypass the require / commonjs dependency.

**Comment by ryepdx** [comment]
Try with the latest version on `master` using `dapple build --template meteor`. Should produce a `meteor.js` file in the `build` directory. Let me know if there are any changes you need made.

**Comment by jorisbontje** [comment]
Looking good!
