### ISSUE TITLE
support libraries

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#197]

**Comment by ryepdx** [comment]
Can you expand on this a little?

**Comment by mhhf** [comment]
I've already begun working on this (#212) and later discovered that delegatecall is not supported in our EtherSim fork. Tim (#184) is working on including it into testrpc and this should work there any time soon. Here we either have to update EtherSim to work with delegatecall as well, or to migrate to testrpc. If this issue has been resolved I can continue with #212.

**Comment by mhhf** [comment]
Closing this - support for test environment is present, deployment on the way,  discussion is here: https://github.com/nexusdev/dapple/issues/212
