### ISSUE TITLE
debug API EIP

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#201]

**Comment by nmushegian** [comment]
related:  https://github.com/nexusdev/dapple/issues/201

**Comment by ryepdx** [comment]
Related: #202

**Comment by ryepdx** [comment]
What endpoints do we want? [TestRPC](https://github.com/ethereumjs/testrpc) already has `evm_snapshot` and `evm_revert`, which could be useful.

Within a testing context some sort of way to set account balances could be very useful. Being able to set keys and addresses for accounts would also be helpful in enabling deterministic and repeatable testing. Something like:

- `evm_importAccount`
- `evm_setBalance`

**Comment by nmushegian** [comment]
* iteratively create transaction sequence
* modify origin between transactions
* commit transaction sequence as a block
* modify block parameters (gaslimit, timestamp, validation rules) between blocks

intuitively there is a head/working state pointer and a head/working block pointer. Each block node refers to a state node, and each state transition requires a block node, possibly associated with a "future" state, for context (for ops like timestamp)

**Comment by ryepdx** [comment]
> iteratively create transaction sequence
> commit transaction sequence as a block

You're thinking of something like Postgres' [transactions](http://www.postgresql.org/docs/8.3/static/tutorial-transactions.html), right? Where the transactions are forked off into their own ephemeral chain so you can essentially preview the state of the main chain if the transactions are committed to it?

> modify origin between transactions

I interpret this to mean being able to change the sending account's metadata.

**Comment by nmushegian** [comment]
> You're thinking of something like Postgres' transactions, right? 

"Transactions" are pretty universal, yes you fork off to create an ephemeral uncommitted-block state, and that block could become a mainnet block or could become a private fork block

> I interpret this to mean being able to change the sending account's metadata. I.e., nonce, balance, maybe even code and storage.

No, only things you can modify when crafting transactions, like the origin or nonce

**Comment by nmushegian** [comment]
implemented in dapple-chain and testrpc
