### ISSUE TITLE
add rpc/integration tests

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#21]
We need a way to test functions that are not callable from solidity

This will also let us control a few factors we can't yet (msg.* and block.*)

**Comment by ryepdx** [comment]
Just read the issue thread you referenced. Can't wait for "Ethereum 2.0..."

My initial impulse is to leverage EtherTDD.py, but that means devs will have to write Python to do RPC/integration tests. This kind of puts us at a disadvantage to Javascript-based tools. Devs are more likely to already be using Javascript in their projects and may be hesitant to integrate yet another language.

I've been mulling over the wisdom of porting Dapple to Node for this reason. My only hesitation there is that we then lose the ability to leverage PyEthereum internally.

Maybe it makes sense to split RPC/integration tests, or even tests in general, out into their own tool. Thoughts?

**Comment by nmushegian** [comment]
Porting to node is OK with me if there is an EVM implementation that is even easier to duck punch than pyethereum's

**Comment by kumavis** [comment]
js evm specifically designed for duck punching

**Comment by ryepdx** [comment]
Yeah, I hear. I'll take a look at what's available. If there isn't one, what are your thoughts regarding splitting out the RPC/integration testing into its own tool?

**Comment by kumavis** [comment]
https://github.com/ethereum/ethereumjs-vm
things are still being factored and moved around a bit but all blockchain state is read/written via the `stateManager` so its easy to overwrite.
 https://github.com/ethereum/ethereumjs-vm/blob/master/lib/stateManager.js
can be overwritten like this:
https://github.com/ConsenSys/blockapps-vm/blob/master/index.js#L10-L12
https://github.com/ConsenSys/blockapps-vm/blob/master/stateManager.js

working on improving the duck punching experience this week

**Comment by nmushegian** [comment]
If rewrite in js isn't an option then I prefer having integration tests be pluggable, with dapple just exposing a rpc for its vm (it can expose bonus functions to manipulate vm state)

**Comment by kumavis** [comment]
let me know what you need in terms of js ethereum stuff, i know where most of the parts are

**Comment by ryepdx** [comment]
@kumavis, is there a repo that demonstrates a working Javascript Ethereum client? We'll need the ability to turn network syncing on and off in order to catch up the client to whatever block height they need to run their tests from and then write the blockchain to disk before forking. Bonus points if there's a way to import the blockchain from `geth` if the user has been running it.

**Comment by kumavis** [comment]
`node-ethereum` has been somewhat neglected in favor of properly building out the underlying components (ethereumjs is rather resource constrained). networking is in progress, but mostly done. the hard part is that its a moving target with new networking versions being introduced all the time.

**Comment by kumavis** [comment]
the main intention is that you'll just use the parts you need and not run a whole client

**Comment by nmushegian** [comment]
What's the best strategy if we want to use a real chain state in the js vm then?

**Comment by kumavis** [comment]
real chain state as in an existing test chain or main net?
right now the best way to do that is to override the StateManager as linked above
I'm working on one that can be backed by any web3 provider, tho no eta currently

**Comment by kumavis** [comment]
( no sleep til devcon! )

**Comment by nmushegian** [comment]
related https://github.com/NexusDevelopment/dapple/issues/63#issuecomment-177105966

**Comment by ryepdx** [comment]
Integrating TestRPC might make this easier

**Comment by mhhf** [comment]
Truffle has nice js based integration testing. We could thing about a cooperation?
Example from [here](http://truffle.readthedocs.org/en/latest/getting_started/testing/): 
```
contract('MetaCoin', function(accounts) {
  it("should put 10000 MetaCoin in the first account", function(done) {
    // Get a reference to the deployed MetaCoin contract, as a JS object.
    var meta = MetaCoin.deployed();

    // Get the MetaCoin balance of the first account, and assert that it's 10000.
    meta.getBalance.call(accounts[0]).then(function(balance) {
      assert.equal(balance.valueOf(), 10000, "10000 wasn't in the first account");
    }).then(done).catch(done);
  });
});
```

**Comment by ryepdx** [comment]
My own feeling is that we should provide a library that handles the contract loading and EVM blockchain spinup rather than wrapping the testing framework as Truffle does. That way developers can use whatever testing framework they prefer instead of being locked into whichever one we've chosen for them. There might be some opportunity for code sharing between our projects, but I really dislike the monolithic approach. Dapple itself already feels too monolithic as it is, TBH, and I look forward to getting it split up into discrete libraries and CLI utilities.

**Comment by nmushegian** [comment]
I think we could separate our VMTest system as a proper dapple package plus supporting javascript library. The default setup harness-level setup should be simplified so that it can be used as a library from other test setups. 

The more important thing to me is ensuring that the integration tests are easy to run on the result of a `dapple run` which sets up a mock system for the package and its dependencies
