### ISSUE TITLE
onboarding wizard

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#215]
to replace dapple config - a wizard which guides the user on the first dapple run (when no .dapplerc is available) through the setup

**Comment by ryepdx** [comment]
In my mind, the prompts we already offer constitute a wizard. What do you have in mind?

**Comment by mhhf** [comment]
Just a random thought I wanted to save. In Spore I had this: https://github.com/mhhf/spore/blob/master/src/lib/setup.es6
Where it "detected" the first run of spore and automatically lead the user through a setup by checking default settings on his machine (e.g. `which ipfs` or `ipfs config show` which provides ip/port configs). Just something to make the user feel comfortable during the first start.

**Comment by mhhf** [comment]
partially implemented for chain in 0.8 and will be improved over the next versions
