### ISSUE TITLE
`dapple test` should default to the `internal` environment

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#232]
`internal` makes sense as a better "default default" for `test`

**Comment by mhhf** [comment]
which dapple version are you using? the newest master branch uses the internal EVM by default

**Comment by nmushegian** [comment]
I think he overrode 'default' in his dappfile which caused dapple test to try to use something other than internal, which doesn't make sense in any context yet

**Comment by jorisbontje** [comment]
Yes, that would be it.

**Comment by mhhf** [comment]
the current master version runs dapple test always on the internal chain regardless of the environment setting. Closing this this is not an one cannot run into this issue anymore.
