### ISSUE TITLE
don't build tests by default

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#241]
`dapple build --tests` to include tests. `dapple test` obviously rebuilds with test.

**Comment by nmushegian** [comment]
The "without tests" variant could also check you aren't accidentally using the `dapple` magic package. Alternatively, we could add `dapple-contracts` aliased as `dapple` by default with `dapple init` and let people actually emit the code for stuff.

**Comment by mhhf** [comment]
Solved in new mhhf/dapple version, will be released with the next PR
