### ISSUE TITLE
Using deploy scripts with Parity

### ISSUE THREAD

**Issue by dbrock** [nexusdev/dapple#251]
Looks like `dapple run` doesn't work with Parity yet:

```
~/src/feedbase$ dapple run deploy/morden.ds -e morden
Using local solc installation...
Deploying to environment "morden"...
Connected to RPC client, block height is 965764
simulated successfully

.
  Invalid params
```

(The same deploy script works with geth.)

**Comment by mhhf** [comment]
Will address this when I dive into parity. Is this urgent for you? Otherwise I'd put it on hold for ~1 Month

**Comment by dbrock** [comment]
Yeah, no, don't worry about it, I can just use geth. I tried looking into it myself but got a bit lost. I might try again later and hit you up on Slack for some advice.

**Comment by harlantwood** [comment]
FWIW I get the same error deploying to Parity from Truffle.  

Some output here: https://gitter.im/ConsenSys/truffle?at=576447faf0528c4c5bb9fa24

**Comment by jorisbontje** [comment]
Can this be fixed? As noted in the linked issue this is because `data` should be prefixed with `0x` https://github.com/ethcore/parity/issues/1317#issuecomment-226985560

Workaround, add `0x` to https://github.com/nexusdev/dapple/blob/master/lib/web3Interface.js#L93

**Comment by dbrock** [comment]
I thought I would release `dapple-0.7.3` to get this out along with #282 but I guess I don't have the requisite `npm` package permissions.
