### ISSUE TITLE
default --optimize on and rename flag to --no-optimize to turn it off

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#253]

**Comment by nmushegian** [comment]
`--no-optimize` can be used by default if there's no native solc. This isn't our primary userbase though!

**Comment by jorisbontje** [comment]
When trying to get the `maker-otc` contract verified on etherscan.io, I noticed that the `solc` optimizer is still disabled in `dapple` by default.

**Comment by nmushegian** [comment]
I wonder if we can compute the cumulative IRL gas cost of this issue

**Comment by mhhf** [comment]
we did a lot of testing with @ryepdx on optimizing performance for dappsys on native solc and in fact optimizing increased compiling time 10x which took ca. 1-2s, which is not nice in a rapid test development.
Maybe we can just make a compromise: `dapple test` is run without optimization by default, everything else like `dapple run` or `dapple build` with optimization by default.

**Comment by mhhf** [comment]
The main reason for the current default was that due to a bug, optimization was never turned on, so after a fix and performance tests we decided to default to no optimization.

**Comment by mhhf** [comment]
in 0.8 code optimization is default on for `dapple script run` and `dapple build`. It can be turned off using the `--no-optimize` flag. For `dapple test` code optimization is off by default and can be turned on with the `--optimize` flag.
