### ISSUE TITLE
`export` of object writes incorrect string to dappfile

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#255]
Running a deploy script which deploys a contract, calls a function on the contract to get an address property and saves the value to a variable, and then exports the variable, results in the following:

```
      alpha_dynasty_multisig:
        class: !<tag:yaml.org,2002:js/undefined> ''
        address: !<tag:yaml.org,2002:js/undefined> ''
```

See `deploy/phase3.morden.deploy` in https://github.com/makerdao/maker-core for an example.

**Comment by mhhf** [comment]
Sadly this is a known problem as DappleScript cannot reason about return types, yet. However, I'm currently in the process of rewriting ds type system so this will be possible soon.

**Comment by mhhf** [comment]
Works in the 0.8 version as new DappleScript is Solidity all type inferences should work.
