### ISSUE TITLE
dapple test should have a flag to filter function names along contract names 

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#260]
Should filtering contract names and function names be done in the same flag or in a different flag?

case 1.1:
split character which splits contract names and function names e.g. `.`
`daple test -r "<contractName>.<functionName>"`
case 1.2:
parameter will match contract names as well as function names
`dapple test -r something`

case 2:
`dapple test --contract <contractfilter> --function <functionfilter>`

or any other suggestions/ thoughts/ wishes?

**Comment by rainbeam** [comment]
I think the same flag. `.` as a separator makes sense: nose uses `module.path:ClassName.function_name`.

Might be useful to allow `-r '*.function_name'` to test same named functions in multiple classes.

**Comment by mhhf** [comment]
This is now supported from v0.8+ with the wildcard notation: `-r '<CONTRACT_FILTER>.<FUNCTION_FILTER>'`
Ground truth:
1. SpecialCase1.testSetup
2. SpecialCase2.testSetupEnvironment
3. SpecialCase2.testSomething
4. SpecialCase21.testSetup
5. SpecialCase3.testSetupEnvironment
examples: 
`dapple test -r 'SpecialCase2*.testSetup'` will match 4
`dapple test -r 'SpecialCase2*.testSetup*'` will match 2, 4
`dapple test -r 'SpecialCase2'` will match 2,3
`dapple test -r '*.testSetupEnv*'` will match 2,5

**Comment by rainbeam** [comment]
@mhhf: awesome!

though I think this breaks the previous behaviour: `dapple test -r specialcase` would have previously matched 1,2,3,4,5 but that appears to not be the case now?

**Comment by mhhf** [comment]
yes, it breaks he behavior to match all you'd need to use `dapple test -r specialcase*`
I added this to provide a way to hit 2,3 but not 4, which you couldn't do previously
