### ISSUE TITLE
had to use sudo..  `sudo npm install -g dapple`

### ISSUE THREAD

**Issue by SilentCicero** [nexusdev/dapple#264]
Perhaps it's a configuration issue, but during my latest install of dapple:

```
npm install -g dapple # or locally: npm install dapple
```

I get:

```
dapple: command not found
```

Everything installed properly, no errors. I had no EACCES errors either. Re: https://docs.npmjs.com/getting-started/fixing-npm-permissions -- not relevant.

I had to use the dreaded `sudo`:

```
sudo npm install -g dapple
```

----

I should be able to install dapple locally, and run the dapple command with little to no problems. It seems the binary just wasn't locally available. Where should the dapple binary be located in the local `node_modules/dapple` folder for example.

This is my `node_modules/dapple` folder `ls -- list`: `cmd  constants  doc  docker-entrypoint  Dockerfile  lib  lib.js  Makefile  mkdocs.yml  node_modules  package.json  README.md  specs  test  watcher`

----

For reference `ethereumjs-testrpc` installs fine locally, and I can run `testrpc` with no issues.

Thoughts?

**Comment by SilentCicero** [comment]
For reference, local use of `dapple` can be done by using:

`node ./node_modules/dapple/cmd/main.js`

**Comment by mhhf** [comment]
I think we resolved it via chat. Closing this. if problems with this still exists, pleas reopen.
