### ISSUE TITLE
No local solc found.

### ISSUE THREAD

**Issue by tjade273** [nexusdev/dapple#266]
I have the "solc" compiler installed, through the Ethereum PPA, and it works firn from the command line, but dapple cannot find the binary and is failing over to the much slower JS compiler.

I am using Ubuntu 14.04 LTS

**Comment by nmushegian** [comment]
@SilentCicero didn't you have this issue?

**Comment by SilentCicero** [comment]
@nmushegian this should be addressed. We should look at how truffle and embark handle their solc compiler. I would say (I should be able to inject or use my own run command for "solc" -- defining how and where it should be run).

**Comment by mhhf** [comment]
hmm @SilentCicero do you think it is sufficient to provide an optional setting in the local `~/.dapplerc`?
I'm thinking of something like this:
```
solc: "/Users/mhhf/bin/solc''
environments:
...
```
Also, what do you mean with defining how it schuld be run? since we are just interested in a combined json file, there is no much space left for customization

**Comment by SilentCicero** [comment]
@mhhf this would be great Dennis. That way I can locally install solc and then select my local install. Love it.

**Comment by tjade273** [comment]
My local solc works now, btw. I'm not sure what changed, but it autodetects correctly now.

**Comment by mhhf** [comment]
Unfortunately this won't get included into 0.7.* but is supported from 0.8+ .
You can configure this setting in `~/.dapple/config` under `state.solc_path`.
