### ISSUE TITLE
tests folder capability/feature

### ISSUE THREAD

**Issue by SilentCicero** [nexusdev/dapple#272]
I would love to be able to have a tests folder, instead of cluttering up my contracts main folder.

Think:
`contracts`
`contracts/tests`

Many coders will also want something like `__tests__` to fit their naming style/conventions. If this becomes a formatting issue, we should be able to set this in `layout` in the `dappfile`.

**Comment by SilentCicero** [comment]
@mhhf would super love this ^^ very needed. Right now, it seems tests have to be beside the contracts in order to be found/run by `dapple`.

**Comment by mhhf** [comment]
Hmm did you failed with this approach?
```
layout:
  sol_sources: contracts
```
sol_sources points just to the top directory which should be scanned for .sol files, so 
´contracts/mycontract.sol` as well as `contracts/verry/long/path/with/a/contract.sol` are both fine.

so a tests directory works just fine.
Just coded a test to verify this: https://github.com/mhhf/layout_test

**Comment by mhhf** [comment]
You can also set 
```
sol_sources: .
```
so your whole directory is scanned. Then you are free to do whatever dir structure you want. Just note that you'll have to declare the imports relative to the root and the scanning will take longer if for example your project is a node project with a lot of directories inside node_modules

**Comment by SilentCicero** [comment]
hmm, weird, okay I'll check @mhhf

**Comment by SilentCicero** [comment]
yep, it works, @mhhf dont know what happened there. So weird.
