### ISSUE TITLE
web3 interface has incorrect (too low) gas limit

### ISSUE THREAD

**Issue by rainbeam** [nexusdev/dapple#273]
Still set to 3141592, but the current limit is more like 4.7M.

https://github.com/nexusdev/dapple/blob/4c4672095b351c984cb274f467870f104078a29d/lib/web3Interface.js#L8

Causes problems with deploying large contracts without `--no-simulation`. Maybe this should be configurable?

**Comment by mhhf** [comment]
increased to 4703192
this is however a temporary fix.
there will be a permanent fix along with dapples new v0.8 features (dapple-chain, dapple-script)
