### ISSUE TITLE
flat-file source for specific contract in package

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#276]
need the ability to export a single .sol file which has a given contract and all of its dependencies, which can be built with a single solc invocation. This helps massively with verification.

notes:
* check that aliasing does not affect deterministic build

**Comment by mhhf** [comment]
Does it have priority? 
Otherwise I'd address this post v0.8 along with refactoring building and linking

**Comment by nmushegian** [comment]
We should do it right, so post 0.8 is fine

**Comment by nmushegian** [comment]
thanks @vessenes https://github.com/nexusdev/dapple/pull/286

**Comment by vessenes** [comment]
Just a note #286 emits contracts with hashes for names; it would be nice to instrument it to emit name-commithash instead; right now in practice it can be a bit tough to parse through the contract output.
