### ISSUE TITLE
Ability to put subpackages directly in the root of the package directory

### ISSUE THREAD

**Issue by dbrock** [nexusdev/dapple#288]
It would be nice if you didn't have to use the somewhat clunky `dapple_packages` (which also conflicts with `dappfile` tab-complete-wise) subdirectory to house your subpackages. Especially since many packages will only even have one or two dependencies (such as `erc20`).

I usually edit my subpackages directly and use them as any normal git repository, so I am constantly navigating up and down the dependency tree and navigating all the extra `dapple_packages` subdirectories that are duplicated everywhere gets old pretty quickly.

Alas, what currently happens if you try to do this is that you get an error such as this:
```
Error: Unable to resolve import path 'erc20/erc20.sol' in file 'contracts/feedbase.sol'
    at Function.resolveImport (/dapple/lib/linker.js:47:11)
    at linked.(anonymous function).source.replace (/dapple/lib/linker.js:83:35)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Function.linkImports (/dapple/lib/linker.js:81:33)
    at Function.link (/dapple/lib/linker.js:14:36)
    at DestroyableTransform._flush (/dapple/lib/streams/linker.js:19:32)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
```

I tried briefly to figure out how to add this but no obvious solution presented itself during my vision quest.

**Comment by mhhf** [comment]
what abut an equivalent of `npm link` command which creates an alias? then you could store your subpackages wherever you want.
as for the directory name: dapple v0.8 uses a local `.dapple` directory. We can move the package directory there (e.g. `./dapple/packages/`)

**Comment by mhhf** [comment]
In v0.8 packages are stored by default in `.dapple/packages/` and are configurable out of the dappfile `layout.packages_directory`. Its possible to store packages at the package Root directory by setting `packages_directory: .`
