### ISSUE TITLE
Error on dapple publish

### ISSUE THREAD

**Issue by shayanb** [nexusdev/dapple#305]
I'm not using ipfs in my contract, however when trying to publish using `dapple publish` I get the following error:

```
/usr/local/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filena

TypeError: Cannot read property 'ipfs' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/dapple/cmd/main.js:309:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by mhhf** [comment]
publish means publish the source code over ipfs as a "package".
you are probably looking for this: http://dapple.readthedocs.io/en/master/dapplescript/

**Comment by shayanb** [comment]
@mhhf I see.
I'm a bit confused here, one issue I had from a while ago is to define environments in dappfile, is it possible to see an example for morden?
I have this now:
```
version: 1.0.0
tags: []
layout:
  sol_sources: contracts
  build_dir: build
dependencies: {}
ignore: []
name: myContract

environments:
    default:
        ethereum:
            host: 'localhost'
            port: '8545'
        morden:
            host: 'localhost'
            port: '8545'
```
which is failing...
```
🍺  dapple run ./dapple_deployscript -e morden
/usr/local/lib/node_modules/dapple/cmd/main.js:260
  let confirmationBlocks = workspace.dappfile.environments[env].confirmationBlocks;
                                                               ^

TypeError: Cannot read property 'confirmationBlocks' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/dapple/cmd/main.js:260:64)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by apmilen** [comment]
[Here](https://github.com/nexusdev/dappsys/blob/develop/Dappfile) is an example of a Dappfile with the environments object defined. It is list of references to already deployed contracts, so dapps that consume this package know where to look for these objects

**Comment by apmilen** [comment]
Also [here](https://github.com/nexusdev/dappsys/blob/develop/legacy/deploy/singletons_0_3_0.morden.ds) is an example of a deployment script that exported these references to the Dappfile

**Comment by shayanb** [comment]
@apmilen thanks. for now Dapple is useless for me as it fails to compile Solidity ^0.4.0 code https://github.com/nexusdev/dapple/issues/310

**Comment by apmilen** [comment]
dapple build is not working but dapple test should be able to compile Solidity ^0.4.0 code

**Comment by apmilen** [comment]
@shayanb

**Comment by mhhf** [comment]
I think that here is a misunderstanding. Dapple is currently in the process of getting migrated to the 0.8 version. You will find it in the 0.8 branch. The current dapple release (0.7.2) is indeed broken with the new solidity and WON'T get updated. Please update your dapple to v0.8 by cloning it from the v0.8 branch and installing it:
```
npm i
npm link
```

**Comment by mhhf** [comment]
There is a new way to write scripts as well. [here](https://github.com/nexusdev/dapple/blob/v0.8/doc/new_features.md) is an overview over the new features such as deploy scripts.

**Comment by shayanb** [comment]
thanks for the explanations. 👍 

 I'll wait until 0.8 official release, I have a system now for deployment that works which I'll stick to it till it doesn't :)
