### ISSUE TITLE
Dapple won't build

### ISSUE THREAD

**Issue by gnidan** [nexusdev/dapple#314]
Fresh install of the project, existing install of solidity, getting weird problems.

```
$ dapple build
Building...
/Users/gnidan/src/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](file
```
(from local git copy, commit 281ab7cc448580aac54b958d92f1d4a0b5b632a2)

I'm on Solidity 0.4.1
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.1+commit.4fc6fc2.Darwin.appleclang
```

**Comment by gnidan** [comment]
Following up: didn't realize it was relevant, but I am trying to follow the example listed in http://dapple.readthedocs.io/en/master/chain/

I realize that the `dappsys` package has all of its code moved to `legacy/` and this is causing problems. Moving everything in `legacy/` out of it doesn't work, first because of the `_` problem, but now I'm getting:

```
/Users/gnidan/src/dapple_play/.dapple/packages/dappsys/contracts/auth/enum.sol:1:1: Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.4.1;".
contract DSAuthModesEnum {
^
Spanning multiple lines.
```
(repeated for a bunch of files)

Which seems to be a problem when I run `solc enum.sol`. The AST builds fine with solc, but `dapple build` isn't outputting anything but errors and a premature EOF:

```
...
/Users/gnidan/src/dapple_play/.dapple/packages/dappsys/contracts/util/false.sol:1:1: Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.4.1;".
contract DSFalseF% 
```

 I assume there is work on getting Dappsys to 0.4.0 or later, but I can't find the active branch for it.

Please advise if there's anything I can do.

**Comment by gnidan** [comment]
Did a bit more digging, got _something_ working, going to close this issue as it is probably meaningless.

**Comment by apmilen** [comment]
Hi @gnidan just thought you'd like to know that dappsys has been broken into numerous smaller packages, to make the dependency process a little less monolithic. They can be found listed here:

https://github.com/nexusdev/

Any repo with the `ds-` prefix will be a dappsys component. I'll get an index site with better package descriptions online soon.
