### ISSUE TITLE
installing dapple on a fresh ubuntu instance fails

### ISSUE THREAD

**Issue by apmilen** [nexusdev/dapple#322]
the `node` binary has been renamed to `nodejs` in ubuntu due to name conflicts. this causes the [install from npm to fail](https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu) because it expects this legacy binary to exist. it would be nice if the install script could support both the `node` and `nodejs` binaries

**Comment by mhhf** [comment]
uffff...
would be interesting to hear some thoughts from @dbrock @ryepdx @nmushegian abut this..
Currently the entry point is /cmd/main.js:
```
#!/usr/bin/env node
```
to resolve this, we would need some wrapper shell script..

**Comment by mhhf** [comment]
Thinking about this more I think this probably won't be fixed -- ubuntu users which use node are familiar with this problem and know their workarounds, and moving the entry point might cause problems with windows.

When did you stumble upon this error?  Is this really that important?

**Comment by apmilen** [comment]
nah you're right ubuntu users probably have their workarounds set already
