### ISSUE TITLE
dapple build and dapple test don't work with the JS compiler and a simple repository

### ISSUE THREAD

**Issue by apmilen** [nexusdev/dapple#323]
Created a simple repository for a dapple tutorial:
https://github.com/apmilen/tokenTest

It silently fails on both commands and emits no build data. `dapple test` emits no test information.

Any idea what could be going wrong?

**Comment by mhhf** [comment]
Shouldn't be silently. In my version an error is printed that https://github.com/nexusdev/erc20/tree/master/contracts don't contain pragma. After adding pragma to erc20, everything compiles fine!
Retry and confirm plz

**Comment by mhhf** [comment]
resolved
