### ISSUE TITLE
More descriptive error on unmatched -r

### ISSUE THREAD

**Issue by rainbeam** [nexusdev/dapple#325]
Using test contract name matching doesn't give a very descriptive error message when there isn't a match:

```
dapple test -r ajsjdsf
Testing...
...
TypeError: Cannot read property 'stop' of undefined
...
```

**Comment by mhhf** [comment]
This should be resolved as for dapple 0.8.5.
If no tests are matched the output will look like this:
```
Testing...

Summary
  Passed all 0 tests!
```
