### ISSUE TITLE
Deployment script failing

### ISSUE THREAD

**Issue by hitchcott** [nexusdev/dapple#328]
I'm attempting to follow along the [new features guide](https://github.com/nexusdev/dapple/blob/master/doc/new_features.md) by implementing a deployment script for a simple [token](https://github.com/apmilen/tokenTest), using solidity 0.4.2.

Only thing I have added to the above repo is `src/tokenDeploy.ds.sol`:

```
pragma solidity ^0.4.2;

import "dapple/script.sol";
import "token.sol";

contract TokenDeploy is Script {
  function TokenDeploy () {
    TestToken token = new TestToken(200);
  }
}
```

When I run `dapple script run TokenDeploy`, it's always failing with the following output:

```
/Users/chris/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=n
invalid JUMP
```

If I comment out the `TestToken token = new TestToken(200);` line, we get `Finished!` with no errors.

I'm aware the docs might be in flux at the moment, perhaps I'm missing some important step? 

Or perhaps this is related to https://github.com/nexusdev/dapple/issues/299#issuecomment-245602327 (`invalid JUMP`)

**Comment by mhhf** [comment]
Unfortunately the Doc your pointed out is the most up to date one. Documentation is already on the list of things we should focus on next.

I could reproduce and resolve the error, you've stubbled on. Can you please install dapple 0.8.8+ and try this again?

**Comment by hitchcott** [comment]
Bingo, working now. Thanks!
