### ISSUE TITLE
seemingly random changes in behavior of compiled contracts

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#339]
https://github.com/nexusdev/ds-token/tree/migrate

`dapple test` vs `dapple test -r DSBalanceDB_Test` have different failing tests

**Comment by nmushegian** [comment]
looks like this has to do with https://github.com/nexusdev/ds-token/pull/2

**Comment by nmushegian** [comment]
When is this fix incoming? https://github.com/ethereumjs/ethereumjs-vm/issues/88

**Comment by mhhf** [comment]
Currently the fix its not on npm. Asked them, will be hopefully pushed soon.

**Comment by mhhf** [comment]
Closing this as vm 2.0.1 is included already. Please reopen if this problem still persists.
