### ISSUE TITLE
TravisCI

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#354]
1) The build has been failing for two weeks. First reason is because of the semistandard linter and second reason is because of a failing test. Both need to be resolved. You can ditch semistandard, as I've said before, but there should definitely be a linter and there should definitely be a uniform coding style enforced. Either way, we shouldn't have failing builds on the `master` branch.

2) TravisCI is running Node 0.6.4 and our package.json specifies Node >= 0.6.5. Not really a huge issue, but the version of Node our CI is running should probably be one of the the versions of Node we claim to support.

**Comment by mhhf** [comment]
1. Fair. I'll stick to semistandard for now as it is not that much of a pain point anymore.  

2. Thanks for pointing that out. I've downgraded the requirement to 6.4
