### ISSUE TITLE
Can't send ether in dapple tests

### ISSUE THREAD

**Issue by chatch** [nexusdev/dapple#374]
See test contract here https://gist.github.com/chatch/bc495971a3a02b213fabb57a4f6da5de/87f4fdf383bee35a932172a4ae691fa585a783d4

Sending ether to other contracts in setUp() or test functions fails. 

Tested with dapple@0.8.36.
Was working with dapple 0.7.2.

**Comment by ethernomad** [comment]
https://github.com/ethereum/solidity/blob/develop/Changelog.md#040-2016-09-08

**Comment by chatch** [comment]
Thanks. Ok so even the fallback needs 'payable'.

Updated contract so now it works : https://gist.github.com/chatch/bc495971a3a02b213fabb57a4f6da5de
