### ISSUE TITLE
Deployment documentation needs updating.

### ISSUE THREAD

**Issue by DennisBPeterson** [nexusdev/dapple#376]
I updated to 0.8.39. According to the docs, use "dapple run ./deployscript", but apparently run isn't supported anymore, dapple just gave me the list of commands. I saw the migrate command so tried "dapple migrate", which said "cannot find dapplerc, aborting!". I also tried "dapple migrate ./deployscript" but got the command list again. I followed the link on the github page to .dapplrc documentation, and got a blank page. I can't find documentation for the Dappfile or ~/.dapple/config.

Straightforward instructions in one place for scripted deployment to the live testnet or mainnet would be very helpful.

**Comment by mhhf** [comment]
Sorry for your experience, as I'm the single maintainer things like proper documentation may fall under the table from time to time. However here is a doc on deployment: https://github.com/nexusdev/dapple/blob/master/doc/new_features.md#dapple-script

Basically we use solidity for deployment scripting! you run it with `dapple script run <ContractName>`

**Comment by DennisBPeterson** [comment]
Cool, I'll give it a shot. It looks like the "dapple script" section should replace this page: http://dapple.readthedocs.io/en/master/dapplescript/

**Comment by mhhf** [comment]
Thank you for pointing this out. changed it http://dapple.readthedocs.io/en/latest/dapplescript/
