### ISSUE TITLE
Replace `solc` compiler to native binary `solc`

### ISSUE THREAD

**Issue by LuoZijun** [nexusdev/dapple#383]
Hi, the  nodejs `solc` compiler speed is very slow, do u have plan to make native binary `solc` compiler is one option ?

**Comment by mhhf** [comment]
Native solc is already supported if you have it in your PATH. js version is only there, to provide a fallback if the native one is not found.
If dapple can't find your solc but you can access it in your default shell, you can enter it manually:
edit `./dapple/config`(json) and set `state.solc` to your custom path

**Comment by LuoZijun** [comment]
@mhhf Oh, thank you.
