### ISSUE TITLE
[brainstorm] vm test enhancements

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#63]
* Right now debug events are only tracked for the test contract itself. They should be tracked either for all contracts, or by selectively `watch`ing them with a new Debug function
* The Test contract should be able to manipulate VM state like block height or timestamp
* The Test contract should get an endowment from the test origin
* `expectEvent` method that expects the next sequence of events fired by the test contract to exactly match the sequence of events fired by all contracts afterwards

So VMTest needs to maintain test harness state

**Comment by ryepdx** [comment]
> The Test contract should be able to manipulate VM state like block height or timestamp

Can you clarify what you have in mind? Do you want this just at the contract and function definition level, or from within the function as well?

**Comment by nmushegian** [comment]
At run time:

```
function testTimeBasedFunction() {
   var first = x.doStuff();
   nextBlock( 15 seconds );
   var second = x.doStuff();
}
```

**Comment by ryepdx** [comment]
Okay. In this example, 15 seconds indicates the time difference you want between the current block's timestamp and the next block's timestamp, is that correct?

**Comment by nmushegian** [comment]
I am anticipating a "debug" json-rpc API extension that will become standardized across all clients. What we create should be written so that eventually it can look like Solidity "system" calls (this sets us up nicely for private blockchain work). We do have to extend the VM, but we could just fail tests that use the extended VM and then it'd be optional and for specific uses.

**Comment by nmushegian** [comment]
We could split this issue into VM extensions and non-extensions. For example a way to "spread" Debug contract tracking via `watch` would be useful.

**Comment by ryepdx** [comment]
- Blockchain closures: pulling in self-contained networks of contracts from the live blockchain and spinning up test blockchains based on them. Might be a nice way to help developers get started on contributing to a blockchain project without having to download the whole blockchain.

**Comment by nmushegian** [comment]
* `tests("...")` modifier for descriptions
* some way of testing interfaces (optionally passing implementation address to setUp or after)

**Comment by nmushegian** [comment]
We need to decide whether we are going all-in on Solidity-based testing or not.

The only real way to do it if we are is to first define a debug abi for testrpc (ethersim) and then make 1:1 hooks in Solidity.

If we aren't, we should decide how to integrate 3rd party tools for testing.

**Comment by nmushegian** [comment]
recent event and exception support: https://github.com/NexusDevelopment/dapple/pull/101

Those are a necessary short-term solution but has some design smells.
