### ISSUE TITLE
utilize solidity linking feature

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#81]
> Heads up for solc integrators: It will soon be possible to automatically import files that are not explicitly specified on the commandline. This might compromise the integrity of your server. Please contact me if you have such a use case.

This should let us delete some linker code. Also serves as a sanity check on our linking design.

**Comment by ryepdx** [comment]
Is there a place I can find out more about this? From just the description here, I'm not entirely convinced it'll let us remove much or any Linker code. Most of the Linker code to do with imports is concerned with resolving paths as either pointing to local code or to code in `dapple_packages`. The command line arguments piece is basically just one line of code.
