### ISSUE TITLE
[proposal] Use "Javascript Standard" style

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#86]
Right now Dapple's code style is a bit inconsistent. I'd like to propose adopting a style guide of some sort. I've seen the [Javascript Standard](https://github.com/feross/standard) style floating around, and it looks as good as any other to me. Plus it has the advantage of having tools available that would allow us to incorporate style checking into our workflow.

Looking for feedback from @nmushegian @mhhf @drupalnomad and anyone else who might consider themselves a stakeholder in this decision.

**Comment by mhhf** [comment]
I like the Idea of a style guide and the one you've picked sounds reasonable to me.
We can at least try this out and see if the adoption comes natural.

However, I'm a little bit sceptical about the "no semicolons" thing. ([airbnb](https://github.com/airbnb/javascript#semicolons) and [google](https://google.github.io/styleguide/javascriptguide.xml#Semicolons) don't agree either)

**Comment by cassiopaia** [comment]
i like it as well! 

> However, I'm a little bit sceptical about the "no semicolons" thing. (airbnb and google don't agree either)

yep ..i would intend to agree @mhhf here

**Comment by ryepdx** [comment]
Alright, so it sounds like [Semistandard](https://github.com/Flet/semistandard) is what we'll go with, unless there are objections from anyone else.

**Comment by cassiopaia** [comment]
+1

**Comment by nmushegian** [comment]
I'll add this to travis if I get help with https://github.com/NexusDevelopment/dapple/issues/109
