### ISSUE TITLE
Allow excluding test classes from build output

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#91]
There should be a way to exclude classes from the build output via regex, similar to the way that we can skip tests by regex. I'm particularly interested in being able to remove test classes from the build output. While we could do this via an interface check like the one @mhhf wrote, leveraging the same flag used by the `test` command seems like a better option than introducing a new one.

**Comment by nmushegian** [comment]
There are two things to discuss here

* "internal" vs "exported" - relevant at the package (contract) level
* suppressing some build output for classes.json and js_module - this is a more general build pipeline issue and the motivation for this issue originally. Maybe also possible via the dappfile, but a prerequisite is a clear definition of required vs optional fields for dappfiles.

**Comment by ryepdx** [comment]
Was addressed with c24e0ea
