### ISSUE TITLE
`dapple step` design issue

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#97]
`dapple step` and `dapple run` commands run transaction steps / sequences written in a DSL. For now, we will use json files much like Embark.

The purpose is to rigorously manage contract system manipulations on chain. By creating a DSL and an engine that executes it instead of simply promoting the use of JS-based deploy scripts we can stop the "sysadmin" from making any mistakes.

The step types are not defined in the most recent usage proposal: https://github.com/NexusDevelopment/dapple/blob/master/docs-old/usage-proposal.md

#### step context

Each step is run in the context of a **named chain connection** ("morden") and a **partial environment** (the constant mapping in the dappfile)

#### Brainstorming distinct step types

TODO distinguish between variables that are to be saved to environment and ones that are used during script execution. Maybe there is no distinction, because where should the "transient" variables be stored? The script should be able to fail at any point and recover the exact state of the system.

`$var1 = deploy TypeName arg1 arg2 ...  [value:N] [gas:M]`

`$var2 = send [TypeName] <address> args ...`

`tmp_result = call $addr args` <- save transient variables for args / asserts

`assert*`  mirroring VMTest. Fail as early as possible if the system enters unexpected state.

`run ...` run sub-sequence

`useKey ...` use a specific private key

`export varName [as objectKeyName]` If as objectKeyName is omitted, the exported name defaults to the name of the variable.

**Comment by nmushegian** [comment]
comment on usage proposal:

I think `step/run ...` should fail if it tries to overwrite any set values. The flag to save should be called `--force`, not `--save`, as step commands are defined to safely modify the dappfile

**Comment by ryepdx** [comment]
Yup, `--force` works for me.

For setting var values, I think `=` is more intuitive and ergonomic than `<-`. Otherwise I do like it.

Also, I propose:

`export varName [as objectKeyName]`

If `as objectKeyName` is omitted, the exported name defaults to the name of the variable.

**Comment by nmushegian** [comment]
added some step types

**Comment by mhhf** [comment]
> By creating a DSL [...] we can stop the "sysadmin" from making any mistakes

1)
Why are the Variables untyped? While the type of an variable can be inferred, it would mane deploy scripts more secure when strict typing is enforced:

```
address $var1 = deploy TypeName...

bool tmp_result = call [TypeName] ...
```

2) 
Is there a good reason to prefer a custom DSL over solidity or a subset of solidity?

**Comment by nmushegian** [comment]
1) I'm in favor of type system. Am I right that our latest "environment" definition is essentially `object_name -> (address, type_name)` which is combined with definitions for the types to form a package? If so there should be no problems.

2) I think it is possible to make this a subset of solidity syntactically but it seems more trouble than it is worth because it fundamentally is a domain-specific language for a different domain where the concepts don't map 1:1.  I'd rather keep it as minimal as possible.

**Comment by mhhf** [comment]
1) yes, object name -> ( address, class_name )

3)
is this equivalent?:
`tmp_result = call $addr args`
`$tmp_result = call $addr <functionName> [args...]`

4) 
where is this script stored relative to the workpath and what should it be called? `./dapploy` :)? 

5)
are several deployscripts possible?:
e.g. `dapple run [<deployscript>]`

I'd like to get my hands on this. Should come up with a draft soon.

**Comment by nmushegian** [comment]
I was thinking `run` executes a sequence of steps and `step` runs a single step by json or DSL statement string.

**Comment by nmushegian** [comment]
3) No:

`tmp_result = call $addr arg`

^ `arg` is raw calldata.

`$tmp_result = call $addr <functionName> [args...]`

^ `functionName` lets you pack the calldata from the given arguments.

**Comment by ryepdx** [comment]
Coming back to the question of how to manage ephemeral variables (and tying into #98 and #211), what if we defined `dapple step`'s output to be a JSON or YAML state object containing all the data necessary to continue execution? Then we'd just have `dapple step` require such an object in order to execute. We could furthermore extend `dapple run` to take such objects in order to continue execution from any given state. There'd have to be some sort of "AST hash" concept to prevent deploy scripts from accidentally being run against state objects from other script, but I think it would work and fit well with this project's overall move toward modularity.

**Comment by ryepdx** [comment]
The state file doesn't necessarily need to be human readable, of course, but it'd be an unusual departure from the rest of the project to make it otherwise.

**Comment by nmushegian** [comment]
This fits very nicely with my understanding of a deploy script "log" which allows you to attempt to restart interrupted sequences more intelligently.
